kind: Service
apiVersion: v1
metadata:
  name: my-project-service
spec:
  selector:
    app: my-project
  type: ClusterIP
  ports:
  - name: apipredict 
    protocol: TCP
    port: 8001
    targetPort: 8000 

